# default options

# standard paths: these are paths to various data dirs and files
# needed for the run; defaults here, per run site, completely
# configurable by the user, via their configuration file
standard-paths:
  jasmin:
    general:
      machinelocation: "JASMIN"
      root_dir: "/gws/ssde/j25a/ukesm"
      shelvedir: "bgcval2/shelves"
      p2p_ppDir: "bgcval2/ukesm_postProcessed"
      imagedir: "bgcval2/images"
      ModelFolder_pref: "BGC_data"
      shared_mass_scripts: "/gws/nopw/j04/esmeval/bgcval2/shared_mass_scripts/"
      orcaGridfn: "/gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc"
      orca1bathy: "/gws/nopw/j04/esmeval/bgc-val/ORCA1bathy.nc"
      ObsFolder: "/gws/nopw/j04/esmeval/example_data/bgc"
    data-files:
      Dustdir: "MahowaldDust/"
      WOAFolder_annual: "WOA/annual/"
      WOAFolder: "WOA/"
      DMSDir: "DMS_Lana2011nc/"
      MAREDATFolder: "MAREDAT/MAREDAT/"
      GEOTRACESFolder: "GEOTRACES/GEOTRACES_PostProccessed/"
      GODASFolder: "GODAS/"
      TakahashiFolder: "Takahashi2009_pCO2/"
      MLDFolder: "IFREMER-MLD/"
      iMarNetFolder: "LestersReportData/"
      GlodapDir: "GLODAP/"
      GLODAPv2Dir: "GLODAPv2/GLODAPv2_Mapped_Climatologies/"
      OSUDir: "OSU/"
      CCIDir: "CCI/"
      icFold: "InitialConditions/"
  monsoon:
    general:
      machinelocation: "MONSOON"
      root_dir: "/projects/ukesm/"
      shelvedir: "shelves"
      p2p_ppDir: "ukesm_postProcessed"
      imagedir: "images"
      ModelFolder_pref: "BGC_data"
      orcaGridfn: "/gws/nopw/j04/esmeval/bgc-val/mesh_mask_eORCA1_wrk.nc"
      # orcaGridfn_file: "mesh_mask_eORCA1_wrk.nc"  # if orcaGridfn not set
      ObsFolder: "/projects/ukesm/"
      # MEDUSAFolder_pref: currently set internally
      # NEMOFolder_pref: currently set internally
    data-files:
      # Dustdir: "MahowaldDust/"
      WOAFolder_annual: "WOA/annual/"
      WOAFolder: "WOA/"
      # DMSDir: "DMS_Lana2011nc/"
      MAREDATFolder: "MAREDAT/MAREDAT/"
      GEOTRACESFolder: "GEOTRACES/GEOTRACES_PostProccessed/"
      # GODASFolder: "GODAS/"
      TakahashiFolder: "Takahashi2009_pCO2/"
      MLDFolder: "IFREMER-MLD/"
      iMarNetFolder: "LestersReportData/"
      GlodapDir: "GLODAP/"
      GLODAPv2Dir: "GLODAPv2/GLODAPv2_Mapped_Climatologies/"
      OSUDir: "OSU/"
      CCIDir: "CCI/"

  pml:
    general:
      machinelocation: "PML"
        #root_dir: "/data/proteus1/scratch/" AMM7
      root_dir: "/data/proteus2/scratch/" # NEMO-ERSEM-eORCA025
      shelvedir: "/data/proteus2/scratch/ledm/bgcval2/shelves"
      p2p_ppDir: "/local1/data/scratch/ledm/bgcval2_postProcessed"
      imagedir: "images"
        #ModelFolder_pref: "gle/dare_baseline" #AMM7
      ModelFolder_pref: "ledm/MissionAtlantic/SENEMO"
      orcaGridfn: "/data/proteus2/scratch/ledm/MissionAtlantic/SENEMO/eORCA025_mesh_mask_mes_v2.nc"
      amm7Gridfn: "/users/modellers/ledm/workspace/coast/AMM7_grid/mesh_mask.nc"  
      ObsFolder: "/data/sthenno1/scratch/ledm/Observations/"
      shared_mass_scripts: "local_test/shared_mass_scripts/"
    data-files:
      Dustdir: "MahowaldDust/"
      WOAFolder_annual: "WOA/annual/"
      WOAFolder: "WOA/"
      DMSDir: "DMS_Lana2011nc/"
      MAREDATFolder: "MAREDAT/MAREDAT/"
      GEOTRACESFolder: "GEOTRACES/GEOTRACES_PostProccessed/"
      GODASFolder: "GODAS/"
      TakahashiFolder: "Takahashi2009_pCO2/"
      MLDFolder: "IFREMER-MLD/"
      iMarNetFolder: "LestersReportData/"
      GlodapDir: "GLODAP/"
      GLODAPv2Dir: "GLODAPv2/GLODAPv2_Mapped_Climatologies/"
      OSUDir: "OSU/"
      CCIDir: "CCI/"
        #icFold: "/data/euryale7/backup/ledm/UKESM/InitialConditions/"
  # to be used only for local automated tests only
  local-test-only:
    general:
      machinelocation: "local-test"
      root_dir: "local_test"
      shelvedir: "bgcval2/shelves"
      p2p_ppDir: "bgcval2/ukesm_postProcessed"
      imagedir: "bgcval2/images"
      ModelFolder_pref: "BGC_data"
      shared_mass_scripts: "local_test/shared_mass_scripts/"
      orcaGridfn: "local_test/mesh_mask_eORCA1_wrk.nc"
      orca1bathy: "local_test/ORCA1bathy.nc"
      ObsFolder: "local_test/bgc"
    data-files:
      Dustdir: "MahowaldDust/"
      WOAFolder_annual: "WOA/annual/"
      WOAFolder: "WOA/"
      DMSDir: "DMS_Lana2011nc/"
      MAREDATFolder: "MAREDAT/MAREDAT/"
      GEOTRACESFolder: "GEOTRACES/GEOTRACES_PostProccessed/"
      GODASFolder: "GODAS/"
      TakahashiFolder: "Takahashi2009_pCO2/"
      MLDFolder: "IFREMER-MLD/"
      iMarNetFolder: "LestersReportData/"
      GlodapDir: "GLODAP/"
      GLODAPv2Dir: "GLODAPv2/GLODAPv2_Mapped_Climatologies/"
      OSUDir: "OSU/"
      CCIDir: "CCI/"
        #icFold: "InitialConditions/"
